### ISSUE TITLE
Patches for vulkan-loader cannot be applied

### ISSUE THREAD

**Issue by crhepner** [m-ab-s/mabs-patches#4]
Several of the affected files in the Vulkan-Loader repository have been updated such that some of the line numbers no longer match.  The patches can thus no longer be applied successfully.  This may be related to #https://github.com/m-ab-s/media-autobuild_suite/issues/2507.

Looking at the patches, the problems seem to be as follows:

- In 0001-loader-cross-compile-static-linking-hacks.patch, the line numbers for /loader/CMakeLists.txt and /loader/vk_loader_platform.h are off. In addition, line 47 of the patch should be deleted, since that line is no longer in /loader/CMakeLists.txt.
- In 0002-pc-remove-CMAKE_CXX_IMPLICIT_LINK_LIBRARIES.patch, the line numbers for /loader/CMakeLists.txt are off.
- In 0003-loader-prefix-cjson-symbols-and-mark-most-as-static.patch, the line numbers for /loader/cJSON.c, /loader/loader.c, and /loader/settings.c are off.

**Comment by 1480c1** [comment]
should be fixed
